vich_uploader:
    db_driver: orm

    mappings:
        carousel:
            uri_prefix: /images/carousel
            upload_destination: '%kernel.project_dir%/public/images/carousel'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        product:
            uri_prefix: /images/menu
            upload_destination: '%kernel.project_dir%/public/images/menu'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        timeline:
            uri_prefix: /images/timeline
            upload_destination: '%kernel.project_dir%/public/images/timeline'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer